#!/bin/sh
# Init script for FastMCP Server provider Docker dev environment.
# Auto-generated by ma-provider-tools — do not edit manually.
set -e

echo "==> Setting up FastMCP Server provider..."

# Run the checked-out MA source, with this provider bind-mounted inside it.
export PYTHONPATH="/ma-server${PYTHONPATH:+:$PYTHONPATH}"
SOURCE_FILE=$(/app/venv/bin/python3 -c "import music_assistant; print(music_assistant.__file__)")
case "$SOURCE_FILE" in
  /ma-server/*) echo "==> MA source overlay: $SOURCE_FILE" ;;
  *) echo "ERROR: MA source overlay is inactive ($SOURCE_FILE)" >&2; exit 1 ;;
esac
echo "==> Provider overlay: /ma-server/music_assistant/providers/fastmcp_server"

# Install provider-specific runtime dependencies (skips music_assistant itself)
DEPS=$(/app/venv/bin/python3 - <<'PYEOF'
import sys
try:
    import tomllib
except ImportError:
    import tomli as tomllib
try:
    with open("/tmp/pyproject.toml", "rb") as f:
        data = tomllib.load(f)
    deps = [
        d for d in data.get("project", {}).get("dependencies", [])
        if not d.lower().startswith("music_assistant")
    ]
    print(" ".join(deps))
except Exception:
    pass
PYEOF
)
if [ -n "$DEPS" ]; then
    echo "==> Installing provider dependencies: $DEPS"
    # The official ghcr.io/music-assistant/server image ships uv but no pip
    # in the venv, so the bare `pip install` path crashes on
    # `/app/venv/bin/pip: not found`. Prefer uv when available; fall back
    # to pip for any image that still has it.
    if [ -x /app/venv/bin/uv ]; then
        /app/venv/bin/uv pip install --quiet --index-strategy unsafe-best-match --python /app/venv/bin/python $DEPS
    else
        /app/venv/bin/pip install --quiet $DEPS
    fi
fi

# Verify that both imported packages resolve from the bind-mounted source tree.
# This catches an image/site-packages fallback before the server accepts a test run.
PROVIDER_FILE=$(/app/venv/bin/python3 -c \
    "import music_assistant.providers.fastmcp_server as provider; print(provider.__file__)")
case "$PROVIDER_FILE" in
  /ma-server/music_assistant/providers/fastmcp_server/*)
    echo "==> Provider source overlay: $PROVIDER_FILE"
    ;;
  *)
    echo "ERROR: provider overlay is inactive ($PROVIDER_FILE)" >&2
    exit 1
    ;;
esac

echo "==> Starting Music Assistant..."
exec /usr/local/bin/entrypoint.sh --data-dir /data --cache-dir /data/.cache
